Repository apiFatec/API-3-Semestre-Ionic, pull requests merged in 2023-10, with the labels that each got.

#13 feat: adiciona campos e valida input cadastrar colaborador
  backend/src/app/users/dto/save-users.dto.ts
  backend/src/app/users/entities/users.entity.ts
  frontend/package.json
  frontend/src/components/BoxInput.tsx
  frontend/src/components/select.tsx
  frontend/src/components/sidebar.tsx
  frontend/src/pages/register/register.tsx
  frontend/src/routes/PrivateRoutes.tsx
  frontend/src/routes/routes.tsx
Labels: help wanted

#22 fix: remove validação do zod
  frontend/src/pages/register/register.tsx
Labels: bug

#26 feat: add entity isos, services and controllers
  backend/src/app.module.ts
  backend/src/app/isos/dto/save-iso.dto.ts
  backend/src/app/isos/entities/isos.entity.ts
  backend/src/app/isos/isos.controller.spec.ts
  backend/src/app/isos/isos.controller.ts
  backend/src/app/isos/isos.module.ts
  backend/src/app/isos/isos.service.spec.ts
  backend/src/app/isos/isos.service.ts
  backend/src/app/tasks/dto/save-task.dto.ts
Labels: feature
